# Generated by Django 6.0 on 2025-12-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchparty',
            name='video_file_path',
        ),
        migrations.AddField(
            model_name='watchparty',
            name='torrent_file',
            field=models.FileField(blank=True, null=True, upload_to='torrents/'),
        ),
    ]
