# Generated by Django 6.0 on 2025-12-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_watchparty_video_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchparty',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchparty',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
    ]
